### ISSUE TITLE
[webpack-cli] Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by alexanderhorner** [laravel-mix/laravel-mix#3207] opened 2022-01-31 22:41 UTC
-   Laravel Mix Version: 6.0.41 (`npm list --depth=0`)
-   Node Version (`node -v`): 16.13.2
-   NPM Version (`npm -v`): 8.1.2
-   OS: macOS Monterey 12.0.1

### Description:

Mix throws weird error even in completely new Laravel project.

### Steps To Reproduce:

1. Create new Laravel Project
2. run `npm install`
3. run `npm run dev`

```console
[webpack-cli] Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at spawn (node:child_process:698:9)
    at Object.execFile (node:child_process:325:17)
    at Object.module.exports.fileCommandJson (/Users/alexanderhorner/Documents/GitHub/wgg-homepage/test/node_modules/node-notifier/lib/utils.js:88:13)
    at NotificationCenter.notifyRaw (/Users/alexanderhorner/Documents/GitHub/wgg-homepage/test/node_modules/node-notifier/notifiers/notificationcenter.js:81:11)
    at WebpackNotifierPlugin.compilationDone (/Users/alexanderhorner/Documents/GitHub/wgg-homepage/test/node_modules/webpack-notifier/index.js:129:14)
    at _next1 (eval at create (/Users/alexanderhorner/Documents/GitHub/wgg-homepage/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:39:1)
    at eval (eval at create (/Users/alexanderhorner/Documents/GitHub/wgg-homepage/test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:63:1) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

**Comment by weavdale** [comment] 2022-02-07 04:32
I'm getting the same error on a new Laravel/Breeze/Vue install.

Laravel Mix Version: 6.0.41
Node Version: 17.4.0
NPM Version 8.4.1
OS: macOS Monterey 12.2 (clean install)

**Comment by thecrypticace** [comment] 2022-02-07 05:16
Duplicate of #3027

We're gonna have to replace a dependency to fix things on ARM macOS it seems.

**Closed by thecrypticace** 2022-02-07 05:16 UTC

**Comment by weavdale** [comment] 2022-02-07 10:38
I installed Rosetta 2 and fixed the problem.
