### ISSUE TITLE
unknown property 'dev' using "run hot"

### ISSUE THREAD

**Issue by XGhozt** [laravel-mix/laravel-mix#2964] opened 2021-05-07 01:52 UTC
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "hot": "mix watch --hot"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "laravel-mix": "^6.0.18"
  },
  "dependencies": {
    "vue": "^2.6.12"
  }
}
```

Then do `npm run hot` and I get this:

Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'dev'. These properties are valid:
   object { bonjour?, client?, compress?, devMiddleware?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }

There's no webpack config and webpack.mix is emtpy.

**Comment by XGhozt** [comment] 2021-05-07 02:15
I've narrowed this down to the `webpack-dev-server` package version `4.0.0-beta.3`.

**Comment by rleger** [comment] 2021-05-07 07:08
Same issue

**Comment by silvioiannone** [comment] 2021-05-07 07:41
I temporarily fixed it by overriding the Webpack configuration generated by Laravel Mix:

    mix.override(config => {
        // Apply a workaround caused by Laravel Mix using the `webpack-dev-server@v4.0.0-beta`:
        // https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.3.
        // Basically the `dev` property has been deprecated in favor of `devMiddleware`.
        if (config.devServer) {
            config.devServer.devMiddleware = config.devServer.dev;
            delete config.devServer.dev;
        }
    });

**Comment by rleger** [comment] 2021-05-07 09:35
> I temporarily fixed it by overriding the Webpack configuration generated by Laravel Mix:
> 
> ```
> mix.override(config => {
>     // Apply a workaround caused by Laravel Mix using the `webpack-dev-server@v4.0.0-beta`:
>     // https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.3.
>     // Basically the `dev` property has been deprecated in favor of `devMiddleware`.
>     if (config.devServer) {
>         config.devServer.devMiddleware = config.devServer.dev;
>         delete config.devServer.dev;
>     }
> });
> ```

Great !! thanks :-)

**Comment by marchershey** [comment] 2021-05-07 11:11
> I temporarily fixed it by overriding the Webpack configuration generated by Laravel Mix:
> 
> ```
> mix.override(config => {
>     // Apply a workaround caused by Laravel Mix using the `webpack-dev-server@v4.0.0-beta`:
>     // https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.3.
>     // Basically the `dev` property has been deprecated in favor of `devMiddleware`.
>     if (config.devServer) {
>         config.devServer.devMiddleware = config.devServer.dev;
>         delete config.devServer.dev;
>     }
> });
> ```

Omg i wanna kiss you. 

Spent 3+ hours on this.. came here to report the bug and noticed the first issue was my issue. 

You have no idea.. my sanity thanks you!

**Comment by thecrypticace** [comment] 2021-05-07 13:50
😱😱😱

We're gonna have to push out a fix for this and lock the version to a specific beta release (… we're on a beta b/c of webpack 5 support). I didn't realize that `^` would upgrade through different beta versions, apologies. I'll see if I can take care of this today. (a PR would be welcome too!)

Plan:
1. Upgrade to latest webpack-dev-server release — pinned to exactly a given version.
2. Fix the config
3. Verify tests pass
4. Release new version

**Comment by thecrypticace** [comment] 2021-05-07 20:58
Tagged 6.0.19. I opted to pin to beta 2 instead of upgrading to beta 3 as I don't have the time at the moment to properly investigate. This should be good to go now though.

**Comment by maxacarvalho** [comment] 2021-06-17 19:52
@thecrypticace I guess this is a problem again, see here [https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#-breaking-changes](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#-breaking-changes)

Is it really necessary to use a beta version?

**Comment by thecrypticace** [comment] 2021-06-17 19:55
@maxacarvalho Sadly, for proper webpack 5 support, it is.

@JeffreyWay I'd intentionally not bumped to beta 3 until I investigated the changes for it. Can we Revert that change or adjust the HMR setup to account for them?

**Comment by maxacarvalho** [comment] 2021-06-17 19:56
@thecrypticace got you. Well, I think it's safe to switch from `dev` to `devMiddleware`.

**Comment by JeffreyWay** [comment] 2021-06-17 20:05
I've temporarily brought it back to beta-2. But, I'd like to bump back up to resolve some audit issues when we can.

**Comment by thecrypticace** [comment] 2021-06-17 20:06
Okay, thanks. I'll spend some time tonight on it so we can bump it.

**Comment by thecrypticace** [comment] 2021-06-17 21:43
@maxacarvalho Can you test the master branch to see if the changes with beta 3 work for you?

**Comment by maxacarvalho** [comment] 2021-06-17 21:47
Hi @thecrypticace yes, it works.

**Comment by thecrypticace** [comment] 2021-06-17 21:48
🙌

**Comment by pad6y** [comment] 2021-08-17 23:17
Anyone know how to fix this error when you try to use 'npm run hot'? Thanks.

[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'webpackbar'. These properties are valid:
   object { bonjour?, client?, compress?, devMiddleware?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }

**Comment by thecrypticace** [comment] 2021-09-09 05:07
The latest version of Mix got rid of that error. We'll have some more HMR fixes coming shortly.

**Closed by thecrypticace** 2021-09-09 05:07 UTC
