### ISSUE TITLE
Help wanted with downstream dependency issue

### ISSUE THREAD

**Issue by Siilwyn** [laravel-mix/laravel-mix#3083] opened 2021-09-02 12:19 UTC
-   Laravel Mix Version: 6.0.29
-   Node Version (`node -v`): 14.17.5
-   NPM Version (`npm -v`): 6.14.14

### Description:
:wave: hi, I'm the maintainer of `css-declaration-sorter` which is a dependency of `cssnano`, some users of `laravel-mix` reported this issue: https://github.com/Siilwyn/css-declaration-sorter/issues/170
Trying to figure out where this is coming from, it seems the issue is not strictly related to `laravel-mix` but it's the only reproducible example I have at the moment. I'm not sure how/where in the process postcss and cssnano are used, it seems like this happens when used with Sass only... Any info, ideas and/or help more than welcome!

### Steps To Reproduce:
https://github.com/Siilwyn/css-declaration-sorter/issues/170#issuecomment-900230576

**Comment by thecrypticace** [comment] 2021-09-02 13:14
I should be able to find some time to look into this over the next few days. Thanks for the report & reproduction. Hopefully we can figure it out.

**Comment by thecrypticace** [comment] 2021-09-03 02:11
So I just took a look and can't reproduce the issue but I guess this was timely because _some_ dependency somewhere updated and it appears to no longer be broken. At least one person in the issue has confirmed. I'd *love* to see a npm or yarn lock file from when the build was broken so we could figure out what actually fixed it.

I'll leave this open until that issue is closed just to be sure.

**Comment by Siilwyn** [comment] 2021-09-03 07:59
Much appreciated @thecrypticace! This is why I love open source.

**Comment by thecrypticace** [comment] 2021-09-06 21:02
Closing as https://github.com/Siilwyn/css-declaration-sorter/issues/170 has been fixed. Thanks!

**Closed by thecrypticace** 2021-09-06 21:02 UTC
Labels: dependencies
