### ISSUE TITLE
`EISDIR: illegal operation on a directory` after `npm run prod`

### ISSUE THREAD

**Issue by maciek-szn** [laravel-mix/laravel-mix#3271] opened 2022-06-03 20:42 UTC
-   Laravel Mix Version: 6.0.45 (`npm list --depth=0`)
-   Node Version (`node -v`): 16.15.0
-   NPM Version (`npm -v`): 8.10.0
-   OS: Windows 10

### Description:

After upgrading to version 6.0.44 or 6.0.45 `npm run prod` command returns error:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at File.read (C:\WWW\laravel\komis\node_modules\laravel-mix\src\File.js:227:19)
    at File.version (C:\WWW\laravel\komis\node_modules\laravel-mix\src\File.js:234:25)
    at Manifest.hash (C:\WWW\laravel\komis\node_modules\laravel-mix\src\Manifest.js:61:74)
    at CustomTasksPlugin.applyVersioning (C:\WWW\laravel\komis\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:110:31)
    at C:\WWW\laravel\komis\node_modules\laravel-mix\src\webpackPlugins\CustomTasksPlugin.js:23:22 {
  errno: -4068,
  syscall: 'read',
  code: 'EISDIR'
}
```

Downgrading to 6.0.43 fixes this issue.

### Steps To Reproduce:

- Upgrade Laravel Mix to 6.0.44 or 6.0.45.
- Use command `npm run prod`

**Comment by thecrypticace** [comment] 2022-06-03 20:44
Welp that shouldn't be possible — could you provide some details about your webpack.mix.js file?

**Comment by maciek-szn** [comment] 2022-06-03 20:48
```
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.setPublicPath('public_html');
mix.version();
mix.extract('public_html/js/vendor.js');
mix.options({ runtimeChunkPath: 'js' });
mix.js('resources/js/app.js', 'public_html/js')
   .js('resources/js/selectize.js', 'public_html/js/app.js')
   .js('node_modules/bootstrap-star-rating/js/star-rating.js', 'public_html/js/app.js')
   .js('node_modules/tablednd/js/jquery.tablednd.js', 'public_html/js/app.js')
   .js('resources/js/modulobox.js', 'public_html/js/app.js')
   .js('resources/js/push.js', 'public_html/js')
   .js('resources/js/pl.js', 'public_html/js/tinymce/pl.js')
   .sass('resources/sass/app-light.scss', 'public_html/css')
   .sass('resources/sass/app-dark.scss', 'public_html/css')
   .sass('resources/sass/modulobox/modulobox.scss', 'public_html/css')
   .postCss('node_modules/bootstrap-star-rating/css/star-rating.css', 'public_html/css');
mix.copyDirectory('resources/img', 'public_html/images');
mix.copyDirectory('node_modules/tinymce/plugins', 'public_html/js/tinymce/plugins');
mix.copyDirectory('node_modules/tinymce/skins', 'public_html/js/tinymce/skins');
mix.copyDirectory('node_modules/tinymce/themes', 'public_html/js/tinymce/themes');
mix.copyDirectory('node_modules/tinymce/icons', 'public_html/js/tinymce/icons');
mix.copyDirectory('resources/tinymce-skins', 'public_html/js/tinymce/skins');
mix.copy('resources/js/serviceworker.js', 'public_html');
mix.copy('node_modules/tinymce/tinymce.min.js', 'public_html/js/tinymce/tinymce.min.js');
mix.copy('node_modules/apexcharts/dist/apexcharts.min.js', 'public_html/js/apexcharts.js');
mix.copy('node_modules/@browser-logos/brave/brave.svg', 'public_html/images/browser-brave.svg');
mix.copy('node_modules/@browser-logos/chrome/chrome.svg', 'public_html/images/browser-chrome.svg');
mix.copy('node_modules/@browser-logos/edge/edge.svg', 'public_html/images/browser-edge.svg');
mix.copy('node_modules/@browser-logos/firefox/firefox.svg', 'public_html/images/browser-firefox.svg');
mix.copy('node_modules/@browser-logos/opera/opera.svg', 'public_html/images/browser-opera.svg');
mix.copy('node_modules/@browser-logos/safari/safari.svg', 'public_html/images/browser-safari.svg');
mix.copy('node_modules/@browser-logos/samsung-internet/samsung-internet.svg', 'public_html/images/browser-samsung-internet.svg');
```

**Comment by thecrypticace** [comment] 2022-06-03 20:49
Thanks! I'll see if I can figure out what's going on and get another point release out this evening.

**Comment by thecrypticace** [comment] 2022-06-03 21:42
I'm having a lot of trouble reproducing this :( Would you mind commenting / uncommenting the copy (and copyDirectory) calls to figure out which ones are causing the issue? And if there's a chance you could provide a reproduction repository that would be _fantastic_

I tried something like this and don't have any issues:

<img width="841" alt="Screen Shot 2022-06-03 at 17 39 58" src="https://user-images.githubusercontent.com/614993/171957435-9e67a31d-7fab-4de4-820a-02f1d6ac3edc.png">

**Comment by maciek-szn** [comment] 2022-06-03 22:23
The problematic line is:

`mix.copy('resources/js/serviceworker.js', 'public_html');`

The issue is fixed after changing it to:

`mix.copy('resources/js/serviceworker.js', 'public_html/serviceworker.js');`

**Comment by thecrypticace** [comment] 2022-06-03 22:25
oh wow okay this is probably a public path normalization issue (… there's a few of those unfortunately) — thanks I think that gives me the info I need

**Comment by superrosko** [comment] 2022-06-03 22:34
I have similar problem on:
- Laravel Mix Version: 6.0.45 (npm list --depth=0)
- Node Version (node -v): 16.15.0
- NPM Version (npm -v): 8.12.1
- OS: Docker image node:16.15.0-alpine

```
[webpack-cli] Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at File.read (/var/www/node_modules/laravel-mix/src/File.js:227:19)
    at File.version (/var/www/node_modules/laravel-mix/src/File.js:234:25)
    at Manifest.hash (/var/www/node_modules/laravel-mix/src/Manifest.js:61:74)
    at CustomTasksPlugin.applyVersioning (/var/www/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:110:31)
    at /var/www/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:23:22 {
     errno: -21,
    syscall: 'read',
    code: 'EISDIR'
}
```

But my problem fix when i removing: `mix.version();`

**Comment by thecrypticace** [comment] 2022-06-03 22:46
Removing `mix.version` makes sense in fixing it because it's the versioning procedure that's failing but as a side effect of something else. I'm still having trouble though. I set up a barebones Laravel project with the latest Mix and a similar structure with public_html and everything and I still can't reproduce it. I have an idea on how to fix it but if my idea / workaround is right the manifest will either have missing or incorrect entries.

**Comment by thecrypticace** [comment] 2022-06-03 22:49
Curious actually… what does your manifest look like when removing `mix.version()`?

**Comment by superrosko** [comment] 2022-06-03 23:17
I have NOT problem on:
- Laravel Mix Version: 6.0.45 (npm list --depth=0)
- Node Version (node -v): 16.15.1
- NPM Version (npm -v): 8.12.1
- OS: Windows 10

My mix-manifest.json on `Windows 10` with `mix.version()`:
```
{
    "/service-worker.js": "/service-worker.js?id=1b37f8a2457dd1d0ddd34013328aece7",
    "/js/app.auth.js": "/js/app.auth.js?id=c11f9bbb66ac11c8011171c39f5df9cb",
    "/js/app.blog.js": "/js/app.blog.js?id=ca346918c42c1b34b104cb49186c5bf3",
    "/js/app.pwa.js": "/js/app.pwa.js?id=56733a47ece5fa7056b08dee1e075326",
....
    "/.htaccess": "/.htaccess?id=3881737db846579f9e86e19352d50773",
    "/manifest.json": "/manifest.json?id=e2f737ff93298799535089923847b984",
    "/mix-manifest.json": "/mix-manifest.json?id=735b5fa1b2720be4bb66b71c3f2a9460",
....
```

My mix-manifest.json on `Docker image node:16.15.0-alpine` without `mix.version()`:
```
{
    "/service-worker.js": "/service-worker.js",
    "/js/app.auth.js": "/js/app.auth.js",
    "/js/app.blog.js": "/js/app.blog.js",
    "/js/app.pwa.js": "/js/app.pwa.js",
....
    "/.htaccess": "/.htaccess",
    "/manifest.json": "/manifest.json",
    "/mix-manifest.json": "/mix-manifest.json",
....
```

My mix-manifest.json on Laravel Mix Version: 6.0.43 generated without `/.htaccess` `/manifest.json` `/mix-manifest.json`
```
{
    "/service-worker.js": "/service-worker.js",
    "/js/app.auth.js": "/js/app.auth.js",
    "/js/app.blog.js": "/js/app.blog.js",
    "/js/app.pwa.js": "/js/app.pwa.js",
```

When i change:
```
mix.js('resources/js/service-worker/service-worker.js', 'public').sourceMaps();
```

on:

```
mix.js(
    'resources/js/service-worker/service-worker.js',
    'public/service-worker.js',
).sourceMaps();
```

file mix-manifest.json  generated without `/.htaccess` `/manifest.json` `/mix-manifest.json` on Laravel Mix Version: 6.0.45 version


The problem appears when using a relative path.
Then mix-manifest.json gets all the files in the destination directory with the version.
But if there are **symlinks** in this directory, then an error occurs.

**Comment by thecrypticace** [comment] 2022-06-03 23:32
The **symlink** was the key piece of information here. Wow okay this is weird. I can reproduce this one now. Now to figure out how to fix it…

**Comment by thecrypticace** [comment] 2022-06-03 23:39
Fixed in https://github.com/laravel-mix/laravel-mix/commit/6cf7e93213481065a44d650510472a578f163dec

v6.0.46 has been published

**Thank you** for helping me figure this one out

**Closed by thecrypticace** 2022-06-03 23:39 UTC
Labels: help wanted, Needs Info
